project:
  type: website

website:
  title: "DevOpsBook2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - eda.qmd
      - model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto